---

_keepalived_checkscript_dir:
  default: "{{ keepalived_data_dir }}/scripts"
  RedHat: "/usr/libexec/keepalived"  # we default to this on RHEL due to pre-set SELinux perms
keepalived_checkscript_dir: "{{ _keepalived_checkscript_dir[ansible_os_family] | default(_keepalived_checkscript_dir['default']) }}"
