# SPDX-License-Identifier: MIT-0
---
# defaults file for keepalived
keepalived_enabled: false

keepalived_vrrp:
  - name: VI_1
    interface: "{{ ansible_default_ipv4['alias'] }}"
    priority: 100
    virtual_router_id: 123
    advert_int: 1
    unicast_src_ip: "{{ ansible_default_ipv4.address }}"  # Shouldn't need to adjust
    unicast_peer: "{{ keepalived_iplist }}" # shouldn't be any need to change this
    vip:
      - "{{ keepalived_vip }}"
    # checkscript: []

keepalived_checkscript_enabled: false
keepalived_checkscript_user: keepalived_script
keepalived_checkscript_group: keepalived_script
keepalived_checkscript_path: "{{ keepalived_checkscript_dir }}"

# keepalived_checkscript_scripts:
#   - name: vault_active_node_script
#     filename: check_vault.py
#     exec: --timeout=1 --url='https://127.0.0.1:8200'
#     content: "{{ lookup('ansible.builtin.file', 'hashicorp/vault/check_vault.py') }}"
#     mode: '0700'
#     interval: 2  # Run script every 2 seconds
#     fall: 1  # If script returns non-zero 2 times in succession, enter FAULT state
#     rise: 3  # If script returns zero r times in succession, exit FAULT state
#     timeout: 2  # Wait up to t seconds for script before assuming non-zero exit code
#     weight: 50  # Reduce priority by 50 on fall
