- name: Deploy KeepAliveD
  hosts:
    - all

  # become: true  # This shouldn't occour at the playbook level
  gather_facts: true

  roles:
    - tfindley.keepalived.keepalived

  vars:
    # keepalived_enabled: true
    # keepalived_vip: 10.181.2.250
    # keepalived_pass:
